name: Create Release

on:
  push:
    branches: [ "An-branch" ]

jobs: 
  build: 
    if: contains(github.event.head_commit.message, 'comment')
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Create release
        id: create-release
        uses: actions/create-releases@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
