name: Create Release

on:
  push:
    branches: [ "An-branch" ]
    
permissions:
  contents: write

jobs: 
  build: 
    name: Create Release
    if: contains(github.event.head_commit.message, 'comment')
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v0.0.1
          release_name: Release v0.0.1
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
