name: Static Analysis 2

on:
  pull_request:
    branches: ["Thinh", "main"]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install pylint
      run: |
        pip install pylint
    - name: Run pylint on src
      run: |
        pylint src/ > pylint-report-src.txt || true

    - name: Run pylint on test
      run: |
        pylint test/ > pylint-report-test.txt || true

    - name: Upload pylint reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pylint-reports
        path: |
          pylint-report-src.txt
          pylint-report-test.txt
