name: Static Analysis

on:
  push:
    branches:
      - hieu-branch

jobs:
  pylint-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install pylint

      - name: Run pylint
        run: |
          . venv/bin/activate
          pylint .