name: Python application

on:
  push: 
    commit: [ "Testing-branch", "main" ]

permissions:
  contents: read
jobs:
  testing_with_unittest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install builder
      run: |
        pipx install poetry
        poetry init
    - name: Run build and test
      run: poetry run python test/test_calculator.py


